version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.2
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    #ulimits:
    #  memlock:
    #    soft: -1
    #    hard: -1
    volumes:
      - /srv/elas1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet

networks:
  esnet:
